### PR TITLE
Test cases from waiting to event driven style

### LINKED ISSUE #273: Decentraland + Gnosis Safe: Create test cases for a failed flow
That flow isn't working because of the highlighted situation:

I) Pre conditions:
-----------------
1. Gnosis safe wallet is funded with enough mana to buy some parcels/estates.
2. Gnosis safe wallet is funded with enough ethers to transfer to ephemeral account.

II) On boarding:
--------------
1. Ephemeral account will be funded with some ethers to pay for gas (from Gnosis safe wallet).
2. Gnosis safe approves ephemeral account to spend their mana tokens.
3. Ephemeral account approves Marketplace to spend their mana tokens (actually tokens from Gnosis Safe). **Not sure if this allowance-of-allowance will work.**

III) Buy operation:
----------------
1. Ephemeral account executes an open order from Marketplace
2. The asset bought will go to the ephemeral account balance.

A test case should be created to cover this case.

The step II.3 doesn't work. The marketplace executes `erc20.transferFrom(msg.sender, ...)` so the ephemeral account should have balance.

**MANAToken**
```solidity
// msg.sender here is the marketplace contract

 function transferFrom(address _from, address _to, uint256 _value) returns (bool) {
   var _allowance = allowed[_from][msg.sender];

   // Check is not needed because sub(_allowance, _value) will already throw if this condition is not met
   // require (_value <= _allowance);

   balances[_to] = balances[_to].add(_value);
   balances[_from] = balances[_from].sub(_value);
   allowed[_from][msg.sender] = _allowance.sub(_value);
   Transfer(_from, _to, _value);
   return true;
 }
```

### PR DESCRIPTION
**Pull request by marcelomorgado**
### Issue link

https://github.com/tasitlabs/TasitSDK/issues/329
https://github.com/tasitlabs/TasitSDK/issues/273
https://github.com/tasitlabs/TasitSDK/issues/219
https://github.com/tasitlabs/TasitSDK/pull/354#discussion_r278745008

### Auto-close the issue?

Closes #273

### Types of changes

Bug fix (non-breaking change that fixes an issue)

Meta (a change that affects future changes to this repo)

Technical debt (a code change that doesn't fix a bug or add a feature but makes something clearer for devs)

### Notes

This change should be extended to all test cases of the project?

### CODE REVIEW

File: packages/tasit-action/src/contract/Action.js [hunk 1]
```diff
@@ -171,7 +169,9 @@ export class Action extends Subscription {
           },
         };
 
+        // Note: Unsubscription should be done after the user's listener function be called
```
Comment (pcowgill) [inline packages/tasit-action/src/contract/Action.js]:
```suggestion
        // Note: Unsubscribing should be done after the user's listener function is called
```

File: packages/tasit-action/src/contract/Action.js [hunk 2]
```diff
@@ -180,16 +180,29 @@ export class Action extends Subscription {
...
-      ethersListener = async blockNumber => {
-        await baseEthersListener(blockNumber);
-        this.off(eventName);
-      };
-    } else {
-      ethersListener = baseEthersListener;
-    }
+    // Note:
+    // On the development env (using ganache-cli)
+    // Blocks are being mined simultaneously and generating a sort of unexpected behaviors like:
```
Comment (pcowgill) [inline packages/tasit-action/src/contract/Action.js]: Maybe if we pick a very, very short but nonzero block time it would help?

File: packages/tasit-action/src/contract/Action.js [hunk 3]
```diff
@@ -180,16 +180,29 @@ export class Action extends Subscription {
...
+    // - sequential blocks giving same confirmation to a transaction
+    // - false-positive reorg event emission
+    // - collaborating for tests non-determinism
+    //
+    // Tech debt:
+    // See if there is another way to avoid these problems, if not
+    // this solution should be improved with a state structure identifying state per event
+    //
+    // Question:
+    // Is possible that behavior (listener concurrency calls for the same event) be desirable?
```
Comment (pcowgill) [inline packages/tasit-action/src/contract/Action.js]:
```suggestion
    // Is it possible that that behavior (listener concurrent calls for the same event) is desirable?
```

File: packages/tasit-action/src/contract/Contract.js [hunk 4]
```diff
@@ -117,9 +117,9 @@ export class Contract extends Subscription {
           },
         };
 
-        if (once) this.off(eventName);
-
+        // Note: Unsubscription should be done after the user's listener function be called
```
Comment (pcowgill) [inline packages/tasit-action/src/contract/Contract.js]:
```suggestion
        // Note: Unsubscripting should be done after the user's listener function is called
```

File: packages/tasit-action/src/contract/Contract.test.js [hunk 5]
```diff
@@ -147,7 +147,7 @@ describe("TasitAction.Contract", () => {
       });
 
       it("and Action error event on action error", async () => {
-        const contractErrorListener = sinon.fake(() => {
+        const contractErrorListener = sinon.fake(error => {
           sampleContract.off("error");
```
Comment (pcowgill) [inline packages/tasit-action/src/contract/Contract.test.js]: We probably don't actually need to remove the error listener in a test like this, right? Is it here because of the instantaneous block times?

File: packages/tasit-action/src/contract/Contract.test.js [hunk 6]
```diff
@@ -175,24 +175,19 @@ describe("TasitAction.Contract", () => {
...
 
         sampleContract.on("error", errorListener);
         sampleContract.on("ValueChanged", eventListener);
 
-        action = sampleContract.setValue("hello world");
-        await action.send();
-
-        await action.waitForOneConfirmation();
-
-        await mineBlocks(provider, 4);
```
Comment (pcowgill) [inline packages/tasit-action/src/contract/Contract.test.js]: It's nice that there are no awaits in here now

File: packages/tasit-action/src/contract/Contract.test.js [hunk 7]
```diff
@@ -541,7 +534,35 @@ describe("TasitAction.Contract", () => {
 
       await mineBlocks(provider, 2);
 
-      expect(confirmationListener.callCount).to.equal(1);
+      // Non-determinitic
+      expect(confirmationListener.callCount).to.be.at.least(1);
+      expect(errorListener.called).to.be.false;
+    });
+
+    it("once listener should be unsubscribed only after user listener function be called", async () => {
```
Comment (pcowgill) [inline packages/tasit-action/src/contract/Contract.test.js]:
```suggestion
    it("once listener should be unsubscribed only after user listener function was called", async () => {
```

File: packages/tasit-action/src/contract/Contract.test.js [hunk 8]
```diff
@@ -541,7 +534,35 @@ describe("TasitAction.Contract", () => {
...
+      });
+
+      const confirmationListener = sinon.fake(message => {
+        console.log(message);
+      });
+
+      action.on("error", errorListener);
+      action.once("confirmation", confirmationListener);
+
+      // Forcing internal (block) listener be called before the transaction be sent
```
Comment (pcowgill) [inline packages/tasit-action/src/contract/Contract.test.js]:
```suggestion
      // Forcing internal (block) listener to be called before the transaction is sent
```

File: packages/tasit-action/src/contract/Action.js (hunk 3 above)
Comment (pcowgill) [reply packages/tasit-action/src/contract/Action.js]: @marcelomorgado This captures your intended meaning, right?

File: packages/tasit-contracts/src/scripts/populateDecentralandContracts.js [hunk 9]
```diff
@@ -252,16 +252,16 @@ const createEstate = async estate => {
...
       action.unsubscribe();
       reject();
     });
 
-    estateContract.on("error", message => {
-      const { error } = message;
-      console.log(error.message);
+    estateContract.on("error", error => {
+      const { message } = error;
+      console.log(message);
```
Comment (pcowgill) [inline packages/tasit-contracts/src/scripts/populateDecentralandContracts.js]: Should it be `console.warn`?

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 10]
```diff
@@ -136,111 +136,176 @@ describe("Decentraland", () => {
...
+              await expectExactTokenBalances(estate, [ephemeralAddress], [1]);
+              done();
+            };
+
+            const errorListener = error => {
+              marketplace.off("error");
+              done(error);
+            };
+
+            // Note: These listener aren't working properly
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]:
```suggestion
            // Note: These listeners aren't working properly
```

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 11]
```diff
@@ -136,111 +136,176 @@ describe("Decentraland", () => {
...
+
+            const orderSuccessfulListener = async message => {
+              const { data } = message;
+              const { args } = data;
+              const { buyer } = args;
+
+              expect(buyer).to.equal(ephemeralAddress);
+              await expectExactTokenBalances(estate, [ephemeralAddress], [1]);
+
+              done();
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]: If this were working properly and it wasn't commented out where this was added, we wouldn't actually want the test to race for two `done`s, right? Instead we would split this out into two tests or pick just one style? Or not call done until both were true?

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 12]
```diff
@@ -136,111 +136,176 @@ describe("Decentraland", () => {
...
+              await expectExactTokenBalances(land, [ephemeralAddress], [1]);
+              done();
+            };
+
+            const errorListener = error => {
+              marketplace.off("error");
+              done(error);
+            };
+
+            // Note: These listener aren't working properly
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]:
```suggestion
            // Note: These listeners aren't working properly
```

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 13]
```diff
@@ -249,393 +314,657 @@ describe("Decentraland", () => {
...
-            seller,
-            priceInWei,
-            expiresAt,
-          } = estateForSale;
+            action.send();
+          })();
+        });
 
-          await checkAsset(estate, mana, estateForSale, ephemeralAddress);
+        beforeEach("onboarding - funding ephemeral wallet with MANA", done => {
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]: Out of curiosity, why not have multiple things happen in a single `beforeEach`?

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 14]
```diff
@@ -249,393 +314,657 @@ describe("Decentraland", () => {
...
+                ephemeralAddress,
+                MARKETPLACE_ADDRESS
+              );
+
+              expect(`${allowance}`).to.equal(`${manaAmountForShopping}`);
+              done();
+            };
+
+            const errorListener = error => {
+              action.off("error");
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]: Any reason this is needed? Maybe as part of test cleanup all listeners should be removed?

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 15]
```diff
@@ -249,393 +314,657 @@ describe("Decentraland", () => {
...
-
-          const buyerAddress = GNOSIS_SAFE_ADDRESS;
-          await checkAsset(estate, mana, estateForSale, buyerAddress);
-
-          await expectExactTokenBalances(estate, [GNOSIS_SAFE_ADDRESS], [0]);
+          const toAddress = ephemeralAddress;
 
-          // Gnosis Safe should execute an open order
+          // Funding ephemeral account with some ethers to pay for gas
           // TODO: ephemeralWallet should broadcast this action
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]: That's an interesting idea - curious for your rationale here

Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Then it's more like a Tasit app clicking a "fund myself" button?

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 16]
```diff
@@ -249,393 +314,657 @@ describe("Decentraland", () => {
...
+            const onFailed = message => {
+              const { data } = message;
+              const { args } = data;
+              const { txHash } = args;
+              done(new Error(`ExecutionFailed event emitted`));
+            };
+
+            const confirmationListener = async message => {
+              // WIP: Not working because of gas issue on Marketplace.safeExecuteOrder() call
+              //await expectExactTokenBalances(estate, [GNOSIS_SAFE_ADDRESS], [1]);
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]: So in other words, we want to be expecting that it's 1, but instead we have to expect that it's 0 until we figure out the gas thing? If so, we can say that even more explicitly in the comments

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 17]
```diff
@@ -249,393 +314,657 @@ describe("Decentraland", () => {
...
+                );
+                expect(`${marketplaceAllowance}`).to.equal(
+                  `${manaAmountForShopping}`
+                );
+                done();
+              };
+
+              const errorListener = error => {
+                action.off("error");
+                done(error);
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]: Isn't this the test `onboarding - approving Marketplace to spend ephemeral account's MANA` where for now we want to assert that it won't work? So should we be doing an expectation here that the error listener is triggered?

Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Oh never mind, I see that that is done below - we're in the beforeEach here, and we're using done() syntax there. Got it.

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 18]
```diff
@@ -249,393 +314,657 @@ describe("Decentraland", () => {
...
+              `${priceInWei}`,
+              `${fingerprint}`
+            );
+
+            const confirmationListener = async message => {
+              // Allowance-of-allowance doesn't work
+              // See more: https://github.com/tasitlabs/TasitSDK/issues/273
+              //await expectExactTokenBalances(estate, [ephemeralAddress], [1]);
+              await expectExactTokenBalances(estate, [ephemeralAddress], [0]);
+              done();
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]: Is there any reason to call `done()` here if we know allowance-of-allowance doesn't work and we won't get to this path? Should we make it `done` with a new error here for now so the test won't pass if it gets here?

File: packages/tasit-sdk/src/Decentraland.test.js [hunk 19]
```diff
@@ -249,393 +314,657 @@ describe("Decentraland", () => {
...
+              action.off("error");
+
+              // Note: once('confirmation') isn't unsubscribing after error emission
+              // See more: https://github.com/tasitlabs/TasitSDK/issues/368
+              action.off("confirmation");
+
+              // Allowance-of-allowance doesn't work
+              // See more: https://github.com/tasitlabs/TasitSDK/issues/273
+              //done(error);
+              done();
```
Comment (pcowgill) [inline packages/tasit-sdk/src/Decentraland.test.js]: We can probably find a clever test helper to use like "assert error listener triggered", etc.

File: packages/tasit-action/src/contract/Action.js (hunk 2 above)
Comment (marcelomorgado) [reply packages/tasit-action/src/contract/Action.js]: I've tried that but not with extremely low block time. I'll make a try.

File: packages/tasit-action/src/contract/Action.js (hunk 3 above)
Comment (marcelomorgado) [reply packages/tasit-action/src/contract/Action.js]: Yep.

File: packages/tasit-contracts/src/scripts/populateDecentralandContracts.js (hunk 9 above)
Comment (marcelomorgado) [reply packages/tasit-contracts/src/scripts/populateDecentralandContracts.js]: Yes, sounds good.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 11 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Are you saying about both `orderSuccessfulListener` and `confirmationListener` on the same test case? If so, we are using only the `confirmationListener`. The intention is to use the `OrderSucessful` event to trigger listener but it isn't working right now (https://github.com/tasitlabs/TasitSDK/issues/367). Because of that, I've added the `confirmationListener` for now.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 13 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Yes, it's related to https://github.com/tasitlabs/tasit/issues/151#issuecomment-474908828 discussion.
I've tried to avoid "callback hell" since these actions are nested.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 14 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Yes, we can move to share `action` var between all test cases and having a cleanup (same as Contract.test.js), but I like the way that it is because reflects better how it's should be used on a real case. Thoughts?

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 15 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Yes.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 16 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Yes. Ok, I'll be more explicitly.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 18 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: I've understood that we want to force them pass (refs: https://github.com/tasitlabs/TasitSDK/issues/273#issuecomment-473977995).
Maybe be more explicitly on the comments? Related to https://github.com/tasitlabs/TasitSDK/pull/369#discussion_r280225416

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 19 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Hmm, I'll take a look.

Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Great - thanks

File: packages/tasit-action/src/contract/Action.js (hunk 3 above)
Comment (pcowgill) [reply packages/tasit-action/src/contract/Action.js]: Okay - can you please include this change in the next PR?

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 11 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Yeah, I'm saying the way it's written right now it's not clear if you'd use both listeners in the same test case, because we kind of are now even though one is commented out.

I think my main preference would be a unit test somewhere that confirms that either method would work in two separate tests. And then in our functional tests throughout the rest of the code, we just use events like you're suggesting.

Maybe include a comment in the code to signal this intent to only use events here in the future?

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 13 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Ah ok. Do these `beforeEach`'s happen sequentially or in parallel.

The other way to avoid "callback hell" in a single `beforeEach` would be to ship marketplace approval and mana funding in parallel, have a separate listener for each that sets local state for whether it has it's response yet, and each time when setting state check if the other one is already done, and if so finish the whole before each.

Is the only callback hell here that we wouldn't want to ship that double action only once the single action of receiving eth had completed?

```js
// buildManaAction here
// buildEthAction here
// buildMarketplaceAction here

functionThatSetsManaDone {
  if (marketplaceDone) {
    functionThatHandlesMarketplaceAndManaDone()
  }
}

functionThatShipsManaAndMarketplaceApproval {
  manaAction.send()
  marketplaceAction.send()
}

ethAction.on('confirmation', functionThatShipsManaAndMarketplaceApproval)
manaAction.on('confirmation', functionThatSetsManaDone)
marketplaceAction.on('confirmation', functionThatSetsMarketplaceDone)

ethAction.send()
```

I guess it is a little confusing to reason about, but as long as we extract the function and define it ahead of time, we're not actually defining functions in a nested way that creates lots of indentation, although there is nesting of program flow.

And we could of course listen for events rather than confirmations above

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 14 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Hmm, so you're saying the user in reality should remove an error listener the moment they get an error? Why? What if there were some second relevant error?

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 15 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: I guess if a user in the Tasit app clicked fund myself, it would still work just as well if it deep-linked into Gnosis Safe app and then the Gnosis Safe app broadcast it, right?

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 16 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Great, thanks!

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 18 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Yeah, we do want to force them to pass. But if we know ahead of time that the code will only flow through one path (the error path) and that's what we want to assert/expect is happening, couldn't we just have one done in the listener for the error path and not here (in the conf listener)?

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 14 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Good point. This is the way that is working now. So, maybe we what that the error listener works always on the "`once` mode"?

Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Hmm wait, I'm still confused - I think we may disagree?

I think users will usually want to listen to errors forever, with some exceptions.

Are you saying that users will usually only want to listen to the first error?

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 15 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: I think so, that test is using the gnosisOwner to call the gnosisSafe contract. So it's like to **not** having the `ephemeral` account as a signer and calling the gnosisSafeApp thru deep-link.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 18 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Ohh, got it. Yes, I agree. I'll remove the `done` from confirmationListener.

Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Awesome, thanks!

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 15 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Yep. So depending on the scope of this particular test, either option is a sensible choice.

Maybe add something from this GitHub comment thread to explain that in addition to the current TODO comment in the code?

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 14 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: I think we maybe will have both situations. Examples:
- Keep `error` listener running and turn it off when the action was successful;
- Turn the `error` listener off if an error occurs (for some reason).
Yes, not make sense unsubscribe after an error emission.


So, answering your question again:

> Any reason this is needed? Maybe as part of test cleanup all listeners should be removed?

You call, I don't have a strong opinion but I like to not have to use global var and having a complete isolated test case.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 15 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Ok, I'll do that.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 14 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: I had a little confusion stemming from picturing how users would use this feature vs. how we want to architect the test suite.

I agree that not having to use a global var in the test suite is nice. So we don't need to create any test cleanup setup that handles cleanup for listeners from all tests.

And I agree that users or our test suite might want to do like you described in both situations above.

What's the problem that we would run into if we kept the error listener subscribed unnecessarily here? Just memory leak at scale? Or intermittent test failures?

Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Long story short - we can keep this line of code as-is, but I'm still curious about the last question for future reference.

File: packages/tasit-action/src/contract/Action.js (hunk 2 above)
Comment (marcelomorgado) [reply packages/tasit-action/src/contract/Action.js]: I've tried these blockTimes: 0.001, 0.01 and 0.1. The lowest values increased the occurrences of the parallel calls.
I guess that could be related to auto block generation for each transaction by `ganache-cli` and maybe this feature could help (https://github.com/trufflesuite/ganache-core/issues/248).
I've open this issue to track that: https://github.com/tasitlabs/TasitSDK/issues/380

File: packages/tasit-action/src/contract/Contract.test.js (hunk 5 above)
Comment (marcelomorgado) [reply packages/tasit-action/src/contract/Contract.test.js]: Right. The `Contract.test.js` differently from `Decentraland.test.js` is cleaning listener between test cases. That will be addressed on a PR that I'm working on.

File: packages/tasit-contracts/src/scripts/populateDecentralandContracts.js (hunk 9 above)
Comment (marcelomorgado) [reply packages/tasit-contracts/src/scripts/populateDecentralandContracts.js]: Solve on https://github.com/tasitlabs/TasitSDK/pull/379

Comment (pcowgill) [reply packages/tasit-contracts/src/scripts/populateDecentralandContracts.js]: Great, thanks! Resolving this.

File: packages/tasit-action/src/contract/Contract.test.js (hunk 5 above)
Comment (pcowgill) [reply packages/tasit-action/src/contract/Contract.test.js]: Okay, great. Thanks for the info and update.

File: packages/tasit-action/src/contract/Action.js (hunk 2 above)
Comment (pcowgill) [reply packages/tasit-action/src/contract/Action.js]: Yep, agreed that that is the most likely cause. I agree that that Ganache feature could help. I added a comment on that issue.

Is the non-determinism mostly for tests where the listener is added before or after sending the tx? Or is it a little of both?

We're sure it's not just getting called again with another confirmation for each instantaneous block, right? If so, we could probably disable that in our code and check number of confirmations on each listener call. Or something like that.

Comment (pcowgill) [reply packages/tasit-action/src/contract/Action.js]: Feel free to move my comment over to that issue instead

Comment (pcowgill) [reply packages/tasit-action/src/contract/Action.js]: If we move it there, we can resolve this thread. Thanks for testing those block times!

Comment (marcelomorgado) [reply packages/tasit-action/src/contract/Action.js]: Comment extracted to issue. Resolving this.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 13 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Extracted to: https://github.com/tasitlabs/TasitSDK/issues/381

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 14 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: > What's the problem that we would run into if we kept the error listener subscribed unnecessarily here? Just memory leak at scale? Or intermittent test failures?

Mocha can be stuck (failing test suite by timeout), not sure but non-determinism can occur since we are using the same provider for all tests on the same test suite.

Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: That makes sense. Thanks. Resolving this.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 13 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Thanks. Resolving this.

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 19 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Extracted to: https://github.com/tasitlabs/TasitSDK/issues/382

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 18 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Done on https://github.com/tasitlabs/TasitSDK/pull/383

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 17 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Could I resolve this?

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 16 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: Done on https://github.com/tasitlabs/TasitSDK/pull/383

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 11 above)
Comment (marcelomorgado) [reply packages/tasit-sdk/src/Decentraland.test.js]: I've splitted the test case and now we have one using contract events and another using action events.

File: packages/tasit-action/src/contract/Contract.test.js (hunk 5 above)
Comment (marcelomorgado) [reply packages/tasit-action/src/contract/Contract.test.js]: Could I close this?

File: packages/tasit-action/src/contract/Action.js (hunk 3 above)
Comment (marcelomorgado) [reply packages/tasit-action/src/contract/Action.js]: Done on https://github.com/tasitlabs/TasitSDK/pull/383 (Now this comment lives on Subscription class)

Comment (pcowgill) [reply packages/tasit-action/src/contract/Action.js]: Thanks! Resolving this.

File: packages/tasit-action/src/contract/Contract.test.js (hunk 5 above)
Comment (pcowgill) [reply packages/tasit-action/src/contract/Contract.test.js]: Yep. Thanks!

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 11 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Great, thanks!! Resolving this

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 16 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Thanks! Resolving this

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 17 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Yep, I'm resolving it now

File: packages/tasit-sdk/src/Decentraland.test.js (hunk 18 above)
Comment (pcowgill) [reply packages/tasit-sdk/src/Decentraland.test.js]: Great, thanks! Resolving this
